# manually provide all citation details

- title: "EXIA: Trusted Transitions for Enclaves via External-Input Attestation"
  authors:
    - Zhen Huang
    - Yidi Kao
    - Sanchuan Chen
    - Guoxing Chen
    - Yan Meng
    - Haojin Zhu
  publisher: NDSS Symposium 2026
  date: 2026-02-01
  link: "https://www.ndss-symposium.org/ndss2026/"
  image: "images/Exia.png"

- title: "Extractions of NLP models with Derivative Analysis"
  authors:
    - Xueqing Zhang
    - Sanchuan Chen
    - Chaoyue Liu
  publisher: DARPA Resilient Software Systems Colloquium
  date: 2025-06-01
  link: "#"
  image: "images/gelu.png"

- title: "Controlled Data Races in Enclaves: Attacks and Detection"
  authors:
    - Sanchuan Chen
    - Zhiqiang Lin
    - Yinqian Zhang
  publisher: USENIX Security Symposium 2023
  date: 2023-01-01
  link: "https://www.usenix.org/conference/usenixsecurity23/presentation/chen-sanchuan"
  image: "images/sgxracer.jpg"

- title: Exploring Value Set Analysis for Binary Code Hardening and Vulnerability Detection
  authors:
    - Sanchuan Chen
  publisher: Ph.D. Dissertation
  date: 2021-01-01
  link: "https://www.proquest.com/dissertations-theses/exploring-value-set-analysis-binary-code/docview/2697183017/se-2"
  image: "images/thesis.jpg"
  
- title: "SelectiveTaint: Efficient Data Flow Tracking With Static Binary Rewriting"
  authors:
    - Sanchuan Chen
    - Zhiqiang Lin
    - Yinqian Zhang
  publisher: USENIX Security Symposium 2021
  date: 2021-01-01
  link: "https://www.usenix.org/conference/usenixsecurity21/presentation/chen-sanchuan"
  image: "images/selectivetaint.jpg"

# manually correct specific citation detail
- id: doi:10.1145/3133956.3134016
  title: "Stacco: Differentially Analyzing Side-Channel Traces for Detecting SSL/TLS Vulnerabilities in Secure Enclaves"
  image: "images/stacco.jpg"
- id: doi:10.1109/eurosp.2019.00020
  image: "images/sgxpectre.jpg"
- id: doi:10.1109/tbdata.2024.3495497
  image: "images/1m.jpg"
- id: doi:10.1145/3052973.3053007
  image: "images/dejavu.jpg"
- id: doi:10.1145/3196494.3196501
  image: "images/lhtm.jpg"
- id: doi:10.1109/sp.2018.00024
  image: "images/hyperrace.jpg"
  

