- id: doi:10.1109/TBDATA.2024.3495497


- id: usenix-sanchuan-chen
  title: Some Publication Title
  authors:
    - "**Steve McQueen**"
    - Lightning McQueen
  publisher: bioRxiv
  date: 2021-01-01
  link: biorxiv.org/1234
