# manually provide all citation details
- title: "Controlled Data Races in Enclaves: Attacks and Detection"
  authors:
    - Sanchuan Chen
    - Zhiqiang Lin
    - Yinqian Zhang
  publisher: USENIX Security Symposium 2023
  date: 2023-01-01
  link: "https://www.usenix.org/conference/usenixsecurity23/presentation/chen-sanchuan"
  image: "images/sgxracer.png"

- title: Exploring Value Set Analysis for Binary Code Hardening and Vulnerability Detection
  authors:
    - Sanchuan Chen
  publisher: Ph.D. Dissertation
  date: 2021-01-01
  link: "https://www.proquest.com/dissertations-theses/exploring-value-set-analysis-binary-code/docview/2697183017/se-2"
  
- title: "SelectiveTaint: Efficient Data Flow Tracking With Static Binary Rewriting"
  authors:
    - Sanchuan Chen
    - Zhiqiang Lin
    - Yinqian Zhang
  publisher: USENIX Security Symposium 2021
  date: 2021-01-01
  link: "https://www.usenix.org/conference/usenixsecurity21/presentation/chen-sanchuan"

# manually correct specific citation detail
- id: doi:10.1145/3133956.3134016
  title: "Stacco: Differentially Analyzing Side-Channel Traces for Detecting SSL/TLS Vulnerabilities in Secure Enclaves"
