# manually provide all citation details
- title: "Controlled Data Races in Enclaves: Attacks and Detection"
  authors:
    - "**Sanchuan Chen**"
    - Zhiqiang Lin
    - Yinqian Zhang
  publisher: USENIX Security Symposium 2023
  date: 2023-01-01

- title: Exploring Value Set Analysis for Binary Code Hardening and Vulnerability Detection
  authors:
    - "**Sanchuan Chen**"
  publisher: Ph.D. Dissertation
  date: 2021-01-01
  
- title: "SelectiveTaint: Efficient Data Flow Tracking With Static Binary Rewriting"
  authors:
    - "**Sanchuan Chen**"
    - Zhiqiang Lin
    - Yinqian Zhang
  publisher: USENIX Security Symposium 2021
  date: 2021-01-01

- title: Some Publication Title
  authors:
    - "**Steve McQueen**"
    - Lightning McQueen
  publisher: bioRxiv
  date: 2021-01-01
  link: biorxiv.org/1234
